sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t extramagnetdavid/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true extramagnetdavid/docker-react npm run test

#deploy:
#  provider: elasticbeanstalk
#  region: "us-east-2"
#  app: "docker-react-esercizio"
#  env: "Dockerreactesercizio-env"
#  bucket_name: "elasticbeanstalk-us-east-2-264856337147"
#  bucket_path: "docker-react-esercizio"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY

